[tool.black]
line-length = 120

[tool.pylint.messages-control]
disable=["missing-module-docstring", "missing-class-docstring", "too-few-public-methods", "too-many-ancestors"]


[tool.pylint.format]
max-line-length = 120
max-module-lines = 1000
