# Generated by Django 4.0 on 2021-12-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientreview",
            options={"verbose_name": "отзыв (карточка на сайте)", "verbose_name_plural": "отзывы (сайт)"},
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Оставьте пустым, чтобы скидка не выводилась",
                null=True,
                verbose_name="Цена по скидке",
            ),
        ),
    ]
