# Generated by Django 3.2.10 on 2021-12-28 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sberbank', '0008_auto_20211228_1751'),
        ('website', '0002_alter_clientreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='sberbank.payment', verbose_name='Оплата (Сбер.)'),
        ),
    ]
