# Generated by Django 3.2.12 on 2022-02-22 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_order_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackcomment',
            options={'verbose_name': 'обратная связь', 'verbose_name_plural': 'обратная связь'},
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.SmallIntegerField(default=0, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.FloatField(verbose_name='Калории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.FloatField(verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extra_picture', to='website.productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.FloatField(verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_picture', to='website.productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.FloatField(verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_categories',
            field=models.ManyToManyField(blank=True, related_name='secondary_categories', to='website.Category', verbose_name='Второстепенные категории'),
        ),
    ]
