# Generated by Django 3.2.12 on 2022-02-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20220222_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostory',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Длительность'),
        ),
    ]
