# Generated by Django 3.2.12 on 2022-02-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_videostory_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostory',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='stories', verbose_name='Загруженное видео'),
        ),
        migrations.AlterField(
            model_name='videostory',
            name='duration',
            field=models.IntegerField(default=0, unique=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='videostory',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
