# Generated by Django 3.2.12 on 2022-02-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20220222_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.SmallIntegerField(unique=True, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='videostory',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Длительность'),
        ),
    ]
