# Generated by Django 4.0 on 2021-12-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="Имя")),
                ("user_id", models.BigIntegerField()),
                ("chat_id", models.BigIntegerField(blank=True, default=None, null=True)),
                ("notifies_on", models.BooleanField(default=True)),
            ],
        ),
    ]
